apiVersion: v1
kind: Service
metadata:
  name: my-country-service
spec:
  type: NodePort
  selector:
    app: country-service    
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30008
      protocol: TCP
